config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  root 'store#index'

  resources :products
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

    def add_product(product_id, product_price)
        current_item = line_items.find_by(product_id: product_id)
        if current_item
        	current_item.quantity += 1
        else
            current_item = line_items.build(product_id: product_id, price: product_price)
        end
         current_item
    end
    def total_price
    	line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
    validates :title, :description, :image_url, presence: true
    validates :price, numericality: {greater_than_or_equal_to: 0.01}
    validates :title, uniqueness: true, length: { minimum: 8 }
    validates :image_url, allow_blank: true, format: {
        with: %r{\.(gif|jpg|jpeg|png)\Z}i,
        message: 'URL должен указывать на изображение формата JPG, PNG, JPEG или GIF.'
    }
    has_many :line_items
    before_destroy :ensure_not_referenced_by_any_line_item

    def self.latest
       Product.order(:updated_at).last
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_url, notice: 'Invalid cart'
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern
   private

  def set_cart
    @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:create]
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id, product.price)

    respond_to do |format|
      if @line_item.save
        session[:counter] = 0
        format.html { redirect_to @line_item.cart, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Your cart is empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :price)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  before_action :set_cart
  def index
  	@count = increment_count
  	@products = Product.order(:title)
  end

  def increment_count
  	session[:counter] ||= 0
  	session[:counter] += 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.slim
h2 Your Cart
table.table
 = render (cart.line_items)
  tr.total_line
    td colspan = 2 Total 
    td.total_cell = number_to_currency(@cart.total_price) 
= button_to 'Опустошить корзину', @cart, class:'btn btn-info', method: :delete, data: {confirm: "Are you sure?"}
= link_to 'Edit', edit_cart_path(@cart), class:'btn btn-info'  
= link_to 'Back', carts_path, class:'btn btn-info'

app/views/carts/_form.html.slim
= form_for @cart do |f|
  - if @cart.errors.any?
    #error_explanation
      h2 = "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      ul
        - @cart.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/carts/edit.html.slim
h1 Editing cart

== render 'form'

= link_to 'Show', @cart
'|
= link_to 'Back', carts_path

app/views/carts/index.html.slim
h1 Listing carts

table
  thead
    tr
      th
      th
      th

  tbody
    - @carts.each do |cart|
      tr
        td = link_to 'Show', cart
        td = link_to 'Edit', edit_cart_path(cart)
        td = link_to 'Destroy', cart, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.slim
h1 New cart

== render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.slim
p#notice = notice
= render @cart

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magazin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
	<div id="banner">
		<%= image_tag("logo.png") %>
	<%= @page_title || "Pragmatic Bookshelf" %>
	</div>
	<div id="columns">
	   <div id="side">
           <div id="cart">
             <%= render @cart %>
           </div>
	     <ul>
			<li><a href="http://www....">Home</a></li>
			<li><a href="http://www..../faq">Questions</a></li>
			<li><a href="http://www..../news">News</a></li>
			<li><a href="http://www..../contact">Contact</a></li>
		 </ul>
		 <div class="times">
		  <%= Time.now %>
		 </div>
		 </div>
	 <div id="main">
	   <%= yield %>
	 </div>
	</div>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Magazin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body.<ruby.code="=.controller.controller_name"></ruby>
    #banner
      = image_tag("logo.png")
      = @page_title || "Pragmatic Bookshelf"
    #columns
      #side      
        ul
          li
            a[href="http://www...."]
              | Home
          li
            a[href="http://www..../faq"]
              | Questions
          li
            a[href="http://www..../news"]
              | News
          li
            a[href="http://www..../contact"]
              | Contact
        .times
          = Time.now
      #main
        = yield

app/views/line_items/_form.html.slim
= form_for @line_item do |f|
  - if @line_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      ul
        - @line_item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :product
    = f.text_field :product
  .field
    = f.label :cart
    = f.text_field :cart
  .actions = f.submit

app/views/line_items/_line_item.slim
- @cart.line_items.each do |item| 
  tr 
    td = item.quantity  
    td = item.product.title
    td = number_to_currency(item.product.price)
    td = button_to 'Удалить товар', item, class:'btn btn-info', method: :delete, data: {confirm: 'Are you sure'} 

app/views/line_items/edit.html.slim
h1 Editing line_item

== render 'form'

= link_to 'Show', @line_item
'|
= link_to 'Back', line_items_path

app/views/line_items/index.html.slim
h1 Listing line_items

table
  thead
    tr
      th Product
      th Cart
      th
      th
      th

  tbody
    - @line_items.each do |line_item|
      tr
        td = line_item.product
        td = line_item.cart
        td = link_to 'Show', line_item
        td = link_to 'Edit', edit_line_item_path(line_item)
        td = link_to 'Destroy', line_item, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.slim
h1 New line_item

== render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.slim
p#notice = notice

p
  strong Product:
  = @line_item.product
p
  strong Cart:
  = @line_item.cart

= link_to 'Edit', edit_line_item_path(@line_item)
'|
= link_to 'Back', line_items_path

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table">
<% @products.each do |product| %>
 <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
 <td>
 <%= image_tag(product.image_url, class: 'list_image') %>
 </td>
 <td class="list_description">
 <dl>
 <dt><%= product.title %></dt>
 <dd><%= truncate(strip_tags(product.description),
 length: 80) %></dd>
 </dl>
 </td>
 <td class="list_actions">
 <%= link_to 'Show', product %><br/>
 <%= link_to 'Edit', edit_product_path(product) %><br/>
 <%= link_to 'Destroy', product, method: :delete,
 data: { confirm: 'Are you sure?' } %>
 </td>
 </tr>
<% end %>
</table>
<br />
<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<div class="head row">
   <h1>Your Pragmatic Catalog</h1>
   <% if session[:counter] > 5 %>
      <h3>This page views <%= pluralize session[:counter], 'time' %></h3>
   <% end %>
</div>
<% cache ['store', Product.latest] do %>
  <% @products.each do |product| %>
    <% cache ['entry', product] do %>
      <div class="entry">
      <br/>
          <%= image_tag(product.image_url) %>
          <h3><%= product.title %></h3>
              <%= sanitize(product.description) %>
          <div class="price_line">
              <span class="price"><%= number_to_currency(product.price, unit: "грн", format: "%n %u") %></span>
              <%= button_to 'Add to Cart', line_items_path(product_id: product), class:'btn btn-info' %>
            </div>
        </div> 
      <% end %>
    <% end %>
  <% end %>